WIP: refine QueueStateGuard and introduce QueueGuard
rust-vmm/vm-virtio pull request #121
Opened 2021-11-22 02:22 UTC by jiangliu

The last two patches tries to:
1) convert `enum QueueStateGuard` to `trait QueueStateGuard` for extensibility and zero-cost abstraction.
2) introduce "struct QueueGuard` to encapsulate a QueueStateGuard object and associated guest memory object.

2021-11-26 05:58 UTC, slp requested changes
Thanks @jiangliu. The trait does indeed look nicer than the enum (perhaps we should do the same in in vhost-user-backend's vring). Could you please rebase this on top of #120 ?

2021-11-26 05:58 UTC, slp commented on crates/virtio-queue/src/queue.rs
> +    fn test_queeu_guard_object() {
Typo here (queeu).

2021-11-26 05:59 UTC, jiangliu commented
> Thanks @jiangliu. The trait does indeed look nicer than the enum (perhaps we should do the same in in vhost-user-backend's vring). Could you please rebase this on top of #120 ?

yes, will handle vhost-user-backend once the virtio-queue settle down:)

2021-11-26 07:17 UTC, jiangliu commented on crates/virtio-queue/src/queue.rs
> +    fn test_queeu_guard_object() {
Fixed

2021-11-26 11:04 UTC, slp submitted a review, later dismissed
LGTM and doesn't break the current API. Nice one @jiangliu

2021-11-29 13:47 UTC, alexandruag reviewed
Just had a few small comments, but otherwise looks good to merge this and then I can rebase some potential changes on top, to have a discussion about how to proceed before publishing 0.1.0 based on pending proposals, including Paolo's PR.

2021-11-29 13:47 UTC, alexandruag commented on crates/virtio-queue/src/queue.rs
> +pub struct QueueGuard<M, S> {
Hmm, could we move `QueueGuard` to its own module as well?

2021-11-29 15:34 UTC, slp approved these changes

2021-11-29 17:37 UTC, alexandruag approved these changes

2021-11-30 09:29 UTC, merged